FROM ubuntu
# Create working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
RUN DEBIAN_FRONTEND=noninteractive apt-get update 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libffi-dev python3-pip python3-tk libopencv-dev python3-opencv mosquitto-clients
RUN pip3 install paho-mqtt
RUN pip3 install boto3
ADD imageprocessor.py /usr/src/app
RUN mkdir -p /usr/src/app/mybucket  
CMD python3 imageprocessor.py